### ISSUE TITLE
Refactor action graph to store stages

### ISSUE THREAD

**Issue by schernichkin** [PROTEINE-INSAIDERS/enki#19]

**Comment by dmitrybugakov** [comment]
А из Stage, можно будет вытащить входные datasets?

**Comment by schernichkin** [comment]
Да. Посмотри функцию stageDependencies, она вытаскивает зависимости (в виде строк) из ReadAction. Аналогичным образом можно вытащить имя таблицы и базу данных.

**Comment by schernichkin** [comment]
c0835ba
